export const SET_STEP = "signUp/SET_STEP";
export const CHANGE_EMAIL = "signUp/CHANGE_EMAIL";
export const CHANGE_RANDOM = "signUp/CHANGE_RANDOM";
export const CHANGE_RANDOM_BTN_STATE = "signUp/CHANGE_RANDOM_BTN_STATE";
export const DECREASE_RANDOM_REMAINING_SECOND = "signUp/DECREASE_RANDOM_REMAINING_SECOND";
export const CHANGE_NICKNAME = "signUp/CHANGE_NICKNAME";
export const CHANGE_PASSWORD = "signUp/CHANGE_PASSWORD";
export const CHANGE_CONFIRM_PASSWORD = "signUp/CHANGE_CONFIRM_PASSWORD";
