export const SET_STEP = "reset/SET_STEP";
export const CHANGE_EMAIL = "reset/CHANGE_EMAIL";
export const CHANGE_RANDOM = "reset/CHANGE_RANDOM";
export const CHANGE_RANDOM_BTN_STATE = "reset/CHANGE_RANDOM_BTN_STATE";
export const DECREASE_RANDOM_REMAINING_SECOND = "reset/DECREASE_RANDOM_REMAINING_SECOND";
export const CHANGE_NICKNAME = "reset/CHANGE_NICKNAME";
export const CHANGE_PASSWORD = "reset/CHANGE_PASSWORD";
export const CHANGE_CONFIRM_PASSWORD = "reset/CHANGE_CONFIRM_PASSWORD";
