export const SWITCH_LOGIN_WAY = "login/SWITCH_LOGIN_WAY";
export const CHANGE_EMAIL = "login/CHANGE_EMAIL";
export const CHANGE_PASSWORD = "login/CHANGE_PASSWORD";
export const CHANGE_RANDOM = "login/CHANGE_RANDOM";
export const CHANGE_RANDOM_BTN_STATE = "login/CHANGE_RANDOM_BTN_STATE";
export const DECREASE_RANDOM_REMAINING_SECOND = "login/DECREASE_RANDOM_REMAINING_SECOND";